import argparse
import os

import pandas as pd

from utils import ensure_dir

PREDICTION_FILE = "output/metrics/predictions.csv"
GROUND_TRUTH_FILE = "data/ground_truth/labels.csv"


def parse_args():
    parser = argparse.ArgumentParser(description="Seed ground truth from prediction boxes for manual review.")
    parser.add_argument("--predictions", default=PREDICTION_FILE, help="Prediction CSV generated by detect_fruits.py")
    parser.add_argument("--output", default=GROUND_TRUTH_FILE, help="Ground-truth CSV to create")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite an existing non-empty output file")
    return parser.parse_args()


def main():
    args = parse_args()

    if not os.path.exists(args.predictions):
        print(f"[ERROR] Prediction file not found: {args.predictions}")
        return

    if os.path.exists(args.output) and os.path.getsize(args.output) > 20 and not args.overwrite:
        print("[ERROR] Output ground-truth file already has content. Use --overwrite if you want to replace it.")
        return

    predictions = pd.read_csv(args.predictions)
    required = ["image", "label", "x", "y", "w", "h"]
    missing = [column for column in required if column not in predictions.columns]
    if missing:
        print(f"[ERROR] Missing columns in prediction file: {', '.join(missing)}")
        return

    seeded = predictions[required].copy()
    seeded = seeded.sort_values(["image", "label", "y", "x"]).reset_index(drop=True)

    ensure_dir(os.path.dirname(args.output))
    seeded.to_csv(args.output, index=False)
    print(f"[DONE] Seeded {len(seeded)} rows to {args.output}")
    print("[INFO] Review and correct the boxes/labels before using them as final ground truth.")


if __name__ == "__main__":
    main()
