import argparse
import os

import pandas as pd

from utils import bbox_iou, ensure_dir

GROUND_TRUTH_FILE = "data/ground_truth/labels.csv"
PREDICTION_FILE = "output/metrics/predictions.csv"
SUMMARY_FILE = "output/metrics/evaluation_summary.csv"
MATCHES_FILE = "output/metrics/matches.csv"


def parse_args():
    parser = argparse.ArgumentParser(description="Evaluate fruit detections with IoU matching.")
    parser.add_argument("--ground-truth", default=GROUND_TRUTH_FILE, help="CSV with columns: image,label,x,y,w,h")
    parser.add_argument("--predictions", default=PREDICTION_FILE, help="CSV generated by detect_fruits.py")
    parser.add_argument("--summary-file", default=SUMMARY_FILE, help="Output CSV for per-class metrics")
    parser.add_argument("--matches-file", default=MATCHES_FILE, help="Output CSV for matched detections")
    parser.add_argument("--iou-threshold", type=float, default=0.5, help="IoU threshold for a true positive")
    return parser.parse_args()


def validate_columns(frame, required, file_path):
    missing = [column for column in required if column not in frame.columns]
    if missing:
        raise ValueError(f"Missing columns in {file_path}: {', '.join(missing)}")


def match_image_rows(gt_rows, pred_rows, iou_threshold):
    remaining_predictions = pred_rows.sort_values("score", ascending=False).copy()
    matches = []

    for gt_idx, gt in gt_rows.iterrows():
        best_pred_idx = None
        best_iou = 0.0

        for pred_idx, pred in remaining_predictions.iterrows():
            if gt["label"] != pred["label"]:
                continue

            iou = bbox_iou(
                (gt["x"], gt["y"], gt["w"], gt["h"]),
                (pred["x"], pred["y"], pred["w"], pred["h"]),
            )
            if iou >= iou_threshold and iou > best_iou:
                best_iou = iou
                best_pred_idx = pred_idx

        if best_pred_idx is None:
            matches.append(
                {
                    "image": gt["image"],
                    "label": gt["label"],
                    "status": "missed_gt",
                    "iou": 0.0,
                    "gt_index": int(gt_idx),
                    "pred_index": "",
                }
            )
            continue

        matches.append(
            {
                "image": gt["image"],
                "label": gt["label"],
                "status": "true_positive",
                "iou": round(best_iou, 4),
                "gt_index": int(gt_idx),
                "pred_index": int(best_pred_idx),
            }
        )
        remaining_predictions = remaining_predictions.drop(index=best_pred_idx)

    for pred_idx, pred in remaining_predictions.iterrows():
        matches.append(
            {
                "image": pred["image"],
                "label": pred["label"],
                "status": "false_positive",
                "iou": 0.0,
                "gt_index": "",
                "pred_index": int(pred_idx),
            }
        )

    return matches


def compute_metrics(matches, classes):
    rows = []

    for label in classes:
        true_positive = sum(item["status"] == "true_positive" and item["label"] == label for item in matches)
        false_positive = sum(item["status"] == "false_positive" and item["label"] == label for item in matches)
        false_negative = sum(item["status"] == "missed_gt" and item["label"] == label for item in matches)

        precision = true_positive / (true_positive + false_positive) if (true_positive + false_positive) else 0.0
        recall = true_positive / (true_positive + false_negative) if (true_positive + false_negative) else 0.0
        f1 = (2 * precision * recall / (precision + recall)) if (precision + recall) else 0.0

        rows.append(
            {
                "label": label,
                "true_positive": true_positive,
                "false_positive": false_positive,
                "false_negative": false_negative,
                "precision": round(precision, 4),
                "recall": round(recall, 4),
                "f1": round(f1, 4),
            }
        )

    return rows


def main():
    args = parse_args()

    if not os.path.exists(args.ground_truth):
        print(f"[ERROR] Ground truth file not found: {args.ground_truth}")
        return

    if not os.path.exists(args.predictions):
        print(f"[ERROR] Prediction file not found: {args.predictions}")
        return

    gt = pd.read_csv(args.ground_truth)
    pred = pd.read_csv(args.predictions)

    required_columns = ["image", "label", "x", "y", "w", "h"]
    validate_columns(gt, required_columns, args.ground_truth)
    validate_columns(pred, required_columns + ["score"], args.predictions)

    if gt.empty:
        print("[ERROR] Ground truth file is empty. Add rows to data/ground_truth/labels.csv before evaluation.")
        return

    matches = []
    for image_name in sorted(set(gt["image"]).union(set(pred["image"]))):
        gt_rows = gt[gt["image"] == image_name].reset_index(drop=False)
        pred_rows = pred[pred["image"] == image_name].reset_index(drop=False)
        matches.extend(match_image_rows(gt_rows, pred_rows, args.iou_threshold))

    classes = sorted(set(gt["label"]).union(set(pred["label"])))
    summary_rows = compute_metrics(matches, classes)
    overall_tp = sum(row["true_positive"] for row in summary_rows)
    overall_fp = sum(row["false_positive"] for row in summary_rows)
    overall_fn = sum(row["false_negative"] for row in summary_rows)
    overall_precision = overall_tp / (overall_tp + overall_fp) if (overall_tp + overall_fp) else 0.0
    overall_recall = overall_tp / (overall_tp + overall_fn) if (overall_tp + overall_fn) else 0.0
    overall_f1 = (2 * overall_precision * overall_recall / (overall_precision + overall_recall)) if (overall_precision + overall_recall) else 0.0
    summary_rows.append(
        {
            "label": "overall",
            "true_positive": overall_tp,
            "false_positive": overall_fp,
            "false_negative": overall_fn,
            "precision": round(overall_precision, 4),
            "recall": round(overall_recall, 4),
            "f1": round(overall_f1, 4),
        }
    )

    ensure_dir(os.path.dirname(args.summary_file))
    pd.DataFrame(summary_rows).to_csv(args.summary_file, index=False)
    pd.DataFrame(matches).to_csv(args.matches_file, index=False)

    print("[INFO] Evaluation summary")
    print(pd.DataFrame(summary_rows).to_string(index=False))
    print(f"[DONE] Saved summary to {args.summary_file}")
    print(f"[DONE] Saved match details to {args.matches_file}")


if __name__ == "__main__":
    main()
